services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      # Anonymous volume to persist node_modules and avoid being overwritten
      - /app/node_modules
    depends_on:
      - backend
